"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 19:33:32.513391
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canonical', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alias_kind'), 'alias', ['kind'], unique=False)
    op.create_table('app_setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('fipe_cache',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('model_spec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumption_city', sa.Float(), nullable=True),
    sa.Column('consumption_road', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('red_flag_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('penalty', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_status',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('blocked_since', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year_fab', sa.Integer(), nullable=True),
    sa.Column('year_model', sa.Integer(), nullable=True),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transmission', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fuel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seller_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('red_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fipe_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fipe_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fipe_price', sa.Integer(), nullable=True),
    sa.Column('fipe_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fipe_diff_pct', sa.Float(), nullable=True),
    sa.Column('fipe_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_brand'), 'vehicle', ['brand'], unique=False)
    op.create_index(op.f('ix_vehicle_model'), 'vehicle', ['model'], unique=False)
    op.create_index(op.f('ix_vehicle_stage'), 'vehicle', ['stage'], unique=False)
    op.create_index(op.f('ix_vehicle_year_model'), 'vehicle', ['year_model'], unique=False)
    op.create_table('alert_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_log_dedupe_key'), 'alert_log', ['dedupe_key'], unique=True)
    op.create_table('kanban_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kanban_event_vehicle_id'), 'kanban_event', ['vehicle_id'], unique=False)
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year_fab', sa.Integer(), nullable=True),
    sa.Column('year_model', sa.Integer(), nullable=True),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('transmission', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fuel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('last_price', sa.Integer(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('neighborhood', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seller_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seller_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('photo_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('missed_runs', sa.Integer(), nullable=False),
    sa.Column('detail_fetched', sa.Boolean(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id')
    )
    op.create_index(op.f('ix_listing_active'), 'listing', ['active'], unique=False)
    op.create_index(op.f('ix_listing_source'), 'listing', ['source'], unique=False)
    op.create_index(op.f('ix_listing_vehicle_id'), 'listing', ['vehicle_id'], unique=False)
    op.create_table('search_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saved_search_id', sa.Integer(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_found', sa.Integer(), nullable=False),
    sa.Column('n_new', sa.Integer(), nullable=False),
    sa.Column('n_price_changes', sa.Integer(), nullable=False),
    sa.Column('n_inactivated', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['saved_search_id'], ['saved_search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_run_saved_search_id'), 'search_run', ['saved_search_id'], unique=False)
    op.create_index(op.f('ix_search_run_source'), 'search_run', ['source'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_listing_id'), 'price_history', ['listing_id'], unique=False)
    op.create_index(op.f('ix_price_history_observed_at'), 'price_history', ['observed_at'], unique=False)
    op.create_table('search_hit',
    sa.Column('saved_search_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['saved_search_id'], ['saved_search.id'], ),
    sa.PrimaryKeyConstraint('saved_search_id', 'listing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_hit')
    op.drop_index(op.f('ix_price_history_observed_at'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_listing_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_search_run_source'), table_name='search_run')
    op.drop_index(op.f('ix_search_run_saved_search_id'), table_name='search_run')
    op.drop_table('search_run')
    op.drop_index(op.f('ix_listing_vehicle_id'), table_name='listing')
    op.drop_index(op.f('ix_listing_source'), table_name='listing')
    op.drop_index(op.f('ix_listing_active'), table_name='listing')
    op.drop_table('listing')
    op.drop_index(op.f('ix_kanban_event_vehicle_id'), table_name='kanban_event')
    op.drop_table('kanban_event')
    op.drop_index(op.f('ix_alert_log_dedupe_key'), table_name='alert_log')
    op.drop_table('alert_log')
    op.drop_index(op.f('ix_vehicle_year_model'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_stage'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_model'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_brand'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_table('source_status')
    op.drop_table('saved_search')
    op.drop_table('red_flag_rule')
    op.drop_table('model_spec')
    op.drop_table('fipe_cache')
    op.drop_table('app_setting')
    op.drop_index(op.f('ix_alias_kind'), table_name='alias')
    op.drop_table('alias')
    # ### end Alembic commands ###
